#!/bin/sh
# Day one, in one command (step 121).
#
#     cd deploy && ./setup.sh
#
# What this is for: everything between `git clone` and a working sign-in used to be
# eight commands, two of which the README warned you about and one of which needed
# another product. None of them was hard. All of them were a reason to close the tab,
# and under a premise that says people install this without an IT department, a
# prerequisite is not a documentation problem — it is the install being lost.
#
# ## Why this is a host script and not a compose service
#
# Because the one thing that has to happen before compose can run at all is the one
# thing no compose service can do. `compose.yaml` marks CARNET_SECRET_KEY as required,
# so while it is unset even `compose build` refuses — and the remedy would need the
# thing it is the remedy for. That `:?` is right and stays: a stack that starts without
# a key is a stack that refuses somebody's credential later, in a sentence about a
# connector rather than about configuration. So the key is generated out here, before
# compose is ever invoked, and written into the file compose reads.
#
# The other half of the install — the tenant, the identity provider row, and the report
# of what is still missing — is `carnet --setup`, which runs as a compose service
# because it needs the database. Two halves, and neither can reach what the other does.
#
# ## What this does NOT do
#
# It does not keep your key. It generates one, prints it, writes it to ./.env at mode
# 600, and that file is the only copy in this deployment. Generating it for you is not
# keeping it, and the sentence that says so is printed at the moment of generation
# rather than left in a README a self-serve installer did not read.
#
# It does not decide your identity provider. It asks, because the failure mode of a
# default there is a company running somebody else's account store for a year without
# having decided to.
set -eu

cd "$(dirname "$0")"
ENV_FILE=.env

say() { printf '%s\n' "$*"; }
refuse() { printf 'setup: %s\n' "$*" >&2; exit 1; }

ask() {
    # prompt, default -> answer on stdout. The default is shown and taken on an empty
    # line, so the whole script is enter-enter-enter for somebody trying it out.
    _prompt=$1
    _default=$2
    if [ -n "$_default" ]; then
        printf '%s [%s]: ' "$_prompt" "$_default" >&2
    else
        printf '%s: ' "$_prompt" >&2
    fi
    read -r _answer || refuse "no answer, and there is no default for that one."
    printf '%s' "${_answer:-$_default}"
}

set_env() {
    # Replace `NAME=` or `#NAME=` wherever it already appears — so the answers land in
    # the section of .env.example that explains them — and append it if it does not.
    #
    # awk with -v rather than sed, and that is not a style preference: the values here
    # are a base64 key, a URL and an email address, and every sed delimiter appears in
    # at least one of them. A generated key containing a `/` breaking the installer it
    # was generated by is the kind of defect that happens once in a hundred runs and
    # cannot be reproduced by the person who reports it.
    #
    # A `$` is doubled on the way in, because compose interpolates this whole file:
    # an organisation called "Acme $Corp" was written verbatim and reached the
    # container as "Acme " — compose expanded `$Corp`, found nothing, and substituted a
    # blank with a warning nobody reads. `$$` is compose's own escape for a literal
    # one. Found by the step's audit; the same hazard .env.example already warns about
    # for the database password, fixed here rather than warned about again.
    awk -v n="$1" -v v="$2" '
        BEGIN { gsub(/\$/, "$$", v) }
        $0 ~ "^#?" n "=" { if (!done) { print n "=" v; done = 1 }; next }
        { print }
        END { if (!done) print n "=" v }
    ' "$ENV_FILE" >"$ENV_FILE.tmp"
    mv "$ENV_FILE.tmp" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
}

is_public_name() {
    # A name ACME can be asked for: something with a dot in it that is not an address.
    # Anything else — `localhost`, a bare hostname, an IP — gets Caddy's own CA, which
    # is what step 109 added `internal` for. Getting this wrong is not a refusal at
    # start but minutes of ACME retries in the front door's log, which is the least
    # legible failure in the whole stack.
    case "$1" in
        *[!0-9.]*) case "$1" in *.*) return 0 ;; *) return 1 ;; esac ;;
        *) return 1 ;;  # digits and dots only: an IPv4 address
    esac
}

# --- before anything is written ------------------------------------------------------

# This one first, ahead of every other check, and the order is the finding rather than
# a preference. It needs nothing — no docker, no terminal — and it is the only true
# thing to say when it is true: with the terminal check ahead of it, somebody piping
# into this script on a deployment that was already set up was told to *copy
# .env.example to .env*, which is advice to create the file that already exists and
# holds their key. Found by the check that asserts the refusal's wording.
#
# Never past this, under any flag, because there is no flag. This file holds the key
# that opens every delegated credential this deployment has stored and there is no copy
# anywhere else, so a setup script that can overwrite one is a setup script that can
# destroy a running deployment's data from a mistyped command.
if [ -e "$ENV_FILE" ]; then
    refuse "$ENV_FILE already exists, so this deployment has been set up. \
\`docker compose up -d\` starts it. If you really are starting over, move that file \
somewhere safe first — it holds CARNET_SECRET_KEY, and every stored credential is \
unreadable without it."
fi

command -v docker >/dev/null 2>&1 || refuse "docker is not on PATH."
docker info >/dev/null 2>&1 || refuse "docker is installed but not running."

[ -t 0 ] || refuse "this asks four questions and there is no terminal to ask on. \
Copy .env.example to .env, fill it in, and run \`docker compose up -d --build\`."

say ""
say "Carnet setup. Four questions, then the stack comes up."
say ""

# --- the questions -------------------------------------------------------------------

domain=$(ask "The address people will reach this at" "localhost")
company=$(ask "Your organisation's name, for the screen" "Carnet")
admin=$(ask "Your email address — you become the first administrator" "")
case "$admin" in
    ?*@?*.?*) ;;
    *) refuse "that does not look like an email address, and it has to match the \
account you will sign in with." ;;
esac

say ""
say "Who signs people in?"
say "  1) Carnet itself — email and password, nothing else to install."
say "     Not a directory: no groups, no provisioning. You can move off it later"
say "     with \`carnet --replace-idp\`."
say "  2) Your own identity provider over OIDC — Okta, Entra, Google, Keycloak."
choice=$(ask "1 or 2" "1")

issuer=""
client_id=""
domains=""
case "$choice" in
    1) idp=bundled ;;
    2)
        idp=external
        issuer=$(ask "  Issuer URL" "")
        [ -n "$issuer" ] || refuse "an external provider needs its issuer URL."
        client_id=$(ask "  Client id of the SPA registered there" "")
        [ -n "$client_id" ] || refuse "an external provider needs a client id."
        # The redirect URI is printed at the END, not here. It contains the port, and
        # the port is not settled until the probe below — so printed here it said
        # `https://localhost/login/callback` for a deployment that turned out to be on
        # 8443, which is a value somebody pastes into Okta and cannot sign in with.
        # Found by the step's own audit, running this branch for the first time.
        domains=$(ask "  Email domains it may create accounts for (comma-separated)" "")
        ;;
    *) refuse "answer 1 or 2." ;;
esac

# --- the key -------------------------------------------------------------------------
#
# Through the image's own `carnet --generate-key` and by no other means. An
# `openssl rand -base64 32` here would be a second implementation of the key format,
# in a second language, drifting against `core/crypto.py` the day KEY_BYTES changes —
# which is the duplication `requirements.lock` and the front door's entrypoint both
# exist to refuse.
#
# Which image is the deployment's existing choice rather than a new one: a team whose
# policy forbids building sets CARNET_API_IMAGE and this pulls it; everybody else gets
# the build compose was going to do anyway.

say ""
image=${CARNET_API_IMAGE:-carnet-api}
if [ -z "${CARNET_API_IMAGE:-}" ]; then
    say "Building the image (once)..."
    docker build -q -t carnet-api --target api -f Dockerfile .. >/dev/null
elif docker image inspect "$image" >/dev/null 2>&1; then
    # Already here, so do not reach for a registry. This is the sealed estate
    # (docs/OFFLINE.md): the images arrived in a tarball and were loaded, there is no
    # registry to pull from, and a `docker pull` would be the one line in this script
    # that needs the internet.
    say "Using $image, already loaded."
else
    say "Pulling $image..."
    docker pull "$image" >/dev/null
fi

key=$(docker run --rm "$image" carnet --generate-key 2>/dev/null)
[ -n "$key" ] || refuse "could not generate an encryption key from $image."

# --- the ports, before anything is written -------------------------------------------
#
# A machine where something already holds 80 is ordinary — another web server, another
# copy of this. Compose finds out at the very last step, after the build and the
# questions, and reports it as `Bind for 0.0.0.0:80 failed` from the Docker daemon,
# which is the least useful moment and the least useful wording. Found by running this
# script on a machine that was already running Carnet.
#
# Probed with `docker run -p` rather than a host-side `nc`, because the binding that
# matters is the DAEMON's: with a VM-backed or remote Docker, the host's view of a port
# is not the one compose will contend for.

port_free() {
    docker run --rm -p "$1:$1" "$image" /bin/true >/dev/null 2>&1
}

http_port=80
https_port=443
if ! port_free 80 || ! port_free 443; then
    say ""
    say "Something on this machine already holds port 80 or 443."
    http_port=$(ask "  HTTP port to use instead" "8080")
    https_port=$(ask "  HTTPS port to use instead" "8443")
    port_free "$http_port" || refuse "port $http_port is taken too."
    port_free "$https_port" || refuse "port $https_port is taken too."
    # ACME's HTTP-01 challenge arrives on the real port 80 at the real name, so a
    # deployment on a shifted port cannot be issued a public certificate however public
    # its name is. Said here rather than discovered as ten minutes of retries in the
    # front door's log.
    shifted=yes
fi

# --- writing .env --------------------------------------------------------------------

cp .env.example "$ENV_FILE"
chmod 600 "$ENV_FILE"

set_env CARNET_SECRET_KEY "$key"
set_env CARNET_DOMAIN "$domain"
set_env CARNET_BOOTSTRAP_ADMIN "$admin"
set_env CARNET_TENANT_NAME "$company"
set_env CARNET_IDP "$idp"

if is_public_name "$domain" && [ -z "${shifted:-}" ]; then
    set_env CARNET_TLS_MODE acme
else
    set_env CARNET_TLS_MODE internal
fi

if [ -n "${shifted:-}" ]; then
    set_env CARNET_HTTP_PORT "$http_port"
    set_env CARNET_HTTPS_PORT "$https_port"
    # The browser's origin now carries a port, and CARNET_PUBLIC_ORIGIN is what every
    # OAuth redirect URI this deployment builds is derived from — including the one the
    # bundled provider registers for sign-in. .env.example says so in its own words;
    # this is that sentence acted on rather than left for somebody to read.
    set_env CARNET_PUBLIC_ORIGIN "https://$domain:$https_port/api"
fi

if [ "$idp" = bundled ]; then
    # Two lines, because compose cannot derive a profile from a variable and a
    # container cannot be told which profiles were activated. Written together here, so
    # the disagreement the front door refuses is one only a hand-editor can create.
    set_env COMPOSE_PROFILES bundled-db,bundled-idp
    set_env CARNET_IDP_REGISTRATION closed
else
    set_env CARNET_OIDC_ISSUER "$issuer"
    set_env CARNET_OIDC_CLIENT_ID "$client_id"
    [ -z "$domains" ] || set_env CARNET_OIDC_DOMAINS "$domains"
fi

say ""
say "================================================================"
say "  Your encryption key:"
say ""
say "      $key"
say ""
say "  Every delegated credential this deployment stores is encrypted"
say "  with it. It is in ./.env (mode 600) and NOWHERE else — we keep"
say "  no copy and there is no recovery. Put it in your password"
say "  manager now, before you go further."
say "================================================================"
say ""
printf 'Press enter once you have stored it. ' >&2
read -r _ || true

# --- up ------------------------------------------------------------------------------

say ""
say "Starting..."
if [ -n "${CARNET_API_IMAGE:-}" ]; then
    docker compose pull --quiet
    docker compose up -d
else
    docker compose up -d --build
fi

say ""
# The setup service is one-shot and ran during `up`; its report is the answer to
# "is this finished", which is the question nobody could previously ask.
docker compose logs setup 2>/dev/null | sed -e 's/^[^|]*| //' || true

url="https://$domain"
[ "$https_port" = 443 ] || url="$url:$https_port"

say ""
if is_public_name "$domain" && [ -z "${shifted:-}" ]; then
    say "Open $url/ and sign in."
else
    say "Open $url/ and sign in. The certificate is signed by this deployment's"
    say "own CA, so your browser will warn once — expected for a name Let's"
    say "Encrypt cannot reach, or a deployment that is not on port 443, because"
    say "ACME's challenge arrives at the real name on the real port. Trusting"
    say "that CA, or bringing your own certificate, is deploy/README.md under"
    say "'Your own certificate'."
fi
if [ "$idp" = external ]; then
    say ""
    say "At $issuer, register this as the SPA's redirect URI — it carries the"
    say "port this deployment actually runs on, and sign-in fails at the last hop"
    say "if it does not match exactly:"
    say ""
    say "    $url/login/callback"
fi
if [ "$idp" = bundled ]; then
    say ""
    say "Registration is CLOSED: the first account is yours, and nobody else can"
    say "create one. Invite colleagues by setting CARNET_IDP_REGISTRATION=open"
    say "in .env, running \`docker compose up -d idp\`, and closing it again."
fi
